### ISSUE TITLE
type object is not subscriptable

### ISSUE THREAD

**Issue by enisimsar** [NickolaiBeloguzov/manokit#1]
Hi, 

thanks for the library!

It gives an error when importing it. 

I tried with version v1.0.0 and v1.1.0 in Python 3.8 env

![image](https://user-images.githubusercontent.com/10683524/112737231-1b6e3200-8f59-11eb-9e13-fafd525bf303.png)

**Comment by NickolaiBeloguzov** [comment]
Hello! 

Sorry for making you waiting. I've just published [v1.1.1](https://github.com/NickolaiBeloguzov/manokit/releases/tag/v1.1.1) that should fix this. Please consider updating your version of manokit. It's already available on [PyPI](https://pypi.org/project/manokit/1.1.1/)

*If you still experience the same or other issues, please let me know*

Again thanks for your patience!
